###############################################################################
#   $URL: http://svnservulm.corp.atmel.com/svn/CDB/Apps/Apps_SW/Trunk/SW_Projects/XC8/ATA8510_FLASH_XC8/ATA8510_FLASH.X/fw_defines.mk $
#   $LastChangedRevision: 660010 $
#   $LastChangedDate: 2022-04-11 15:45:34 +0200 (Mo, 11 Apr 2022) $
#   $LastChangedBy: gwillbol $
###############################################################################

ADD_LINKER_FLAGS += -Wl,-Tata8510_curiosity.xn
ADD_LINKER_FLAGS += -Wl,-Tdata=0x800488


ADD_LINKER_FLAGS   += -Wl,--defsym=JMPTABLE=0x0A80
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ReadFillLevelRxBuffer_C=0x180
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ReadFillLevelTxBuffer_C=0x186
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ReadFillLevelRssiBuffer_C=0x18C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_GetEventBytes_C=0x192
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ReadRssiBuffer_C=0x1B6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ReadRxBuffer_C=0x1EC
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_WriteSramRegisters_C=0x222
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ReadSramRegisters_C=0x23E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_WriteEeprom_C=0x25A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ReadEeprom_C=0x25E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_WriteTxBuffer_C=0x262
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_WriteTxPreambleBuffer_C=0x286
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_SetSystemMode_C=0x2AA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_CalibrateAndCheck_C=0x2B6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_GetRomVersion_C=0x2C0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_GetFlashVersion_C=0x2C4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_CustomerConfigurableCommand_C=0x2E6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_SystemReset_C=0x2F0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_TriggerEepromSecureWrite_C=0x2FE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_SetVoltageMonitor_C=0x306
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_OffCommand_C=0x35C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ReadTemperature_C=0x374
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_InitSramService_C=0x37E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_StartRssiMeasurement_C=0x38A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_GetRssiAverageValue_C=0x39A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_GetRssiPeakValue_C=0x3A0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ReadFillLevelRxBuffer_C=0x5A00
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ReadFillLevelTxBuffer_C=0x5A04
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ReadFillLevelRssiBuffer_C=0x5A08
ADD_LINKER_FLAGS   += -Wl,--defsym=API_GetEventBytes_C=0x5A0C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ReadRssiBuffer_C=0x5A10
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ReadRxBuffer_C=0x5A14
ADD_LINKER_FLAGS   += -Wl,--defsym=API_WriteSramRegisters_C=0x5A18
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ReadSramRegisters_C=0x5A1C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_WriteEeprom_C=0x5A20
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ReadEeprom_C=0x5A24
ADD_LINKER_FLAGS   += -Wl,--defsym=API_WriteTxBuffer_C=0x5A28
ADD_LINKER_FLAGS   += -Wl,--defsym=API_WriteTxPreambleBuffer_C=0x5A2C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_SetSystemMode_C=0x5A30
ADD_LINKER_FLAGS   += -Wl,--defsym=API_CalibrateAndCheck_C=0x5A34
ADD_LINKER_FLAGS   += -Wl,--defsym=API_GetRomVersion_C=0x5A38
ADD_LINKER_FLAGS   += -Wl,--defsym=API_GetFlashVersion_C=0x5A3C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_CustomerConfigurableCommand_C=0x5A40
ADD_LINKER_FLAGS   += -Wl,--defsym=API_SystemReset_C=0x5A44
ADD_LINKER_FLAGS   += -Wl,--defsym=API_TriggerEepromSecureWrite_C=0x5A48
ADD_LINKER_FLAGS   += -Wl,--defsym=API_SetVoltageMonitor_C=0x5A4C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_OffCommand_C=0x5A50
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ReadTemperature_C=0x5A54
ADD_LINKER_FLAGS   += -Wl,--defsym=API_InitSramService_C=0x5A58
ADD_LINKER_FLAGS   += -Wl,--defsym=API_StartRssiMeasurement_C=0x5A5C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_GetRssiAverageValue_C=0x5A60
ADD_LINKER_FLAGS   += -Wl,--defsym=API_GetRssiPeakValue_C=0x5A64
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rfCalibration_C=0x5A68
ADD_LINKER_FLAGS   += -Wl,--defsym=API_anttuneStateInitSSM_C=0x5A6C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_sysAntTuneSsmEnable_C=0x5A70
ADD_LINKER_FLAGS   += -Wl,--defsym=API_anttuneStateStartSSM_C=0x5A74
ADD_LINKER_FLAGS   += -Wl,--defsym=API_anttuneStateWait4SSMrdy_C=0x5A78
ADD_LINKER_FLAGS   += -Wl,--defsym=API_anttuneStateSetCmdRdy_C=0x5A7C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_vcocalStateInitSSM_C=0x5A80
ADD_LINKER_FLAGS   += -Wl,--defsym=API_sysVcoCalSsmEnable_C=0x5A84
ADD_LINKER_FLAGS   += -Wl,--defsym=API_vcocalStateStartSSM_C=0x5A88
ADD_LINKER_FLAGS   += -Wl,--defsym=API_vcocalStateWait4SSMrdy_C=0x5A8C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_vcocalStateSetCmdRdy_C=0x5A90
ADD_LINKER_FLAGS   += -Wl,--defsym=API_tempmeasStateInitSSM_C=0x5A94
ADD_LINKER_FLAGS   += -Wl,--defsym=API_sysTempMeasSsmEnable_C=0x5A98
ADD_LINKER_FLAGS   += -Wl,--defsym=API_tempmeasStateStartSSM_C=0x5A9C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_tempmeasStateWait4SSMrdy_C=0x5AA0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_tempmeasStateWait4Temperature_C=0x5AA4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_tempmeasStateSetCmdRdy_C=0x5AA8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_eepWRbyte_C=0x5AAC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_eepWRblock_C=0x5AB0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_eepRDblock_C=0x5AB4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_eepromSecureWrite_C=0x5AB8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_eepRDbyte_ASM=0x5ABC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_SpiOpen_C=0x5AC0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_initExtIf_C=0x5AC4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_PatchSpiReady_ASM=0x5AC8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pinChangeInterrupt0Handler_ASM=0x5ACC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pinChangeInterrupt1Handler_ASM=0x5AD0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_SpiClose_ASM=0x5AD4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_spiSerialTransferCompleteHandler_ASM=0x5AD8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_spiRxBufferHandler_ASM=0x5ADC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_spiTxBufferHandler_ASM=0x5AE0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_portBisr_ASM=0x5AE4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_portCisr_ASM=0x5AE8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_interrupt0Handler_ASM=0x5AEC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_interrupt1Handler_ASM=0x5AF0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_setClk_C=0x5AF4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_wdtDisable_C=0x5AF8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_wdtEnable_C=0x5AFC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_SleepMode_C=0x5B00
ADD_LINKER_FLAGS   += -Wl,--defsym=API_Sleep_C=0x5B04
ADD_LINKER_FLAGS   += -Wl,--defsym=API_currentServiceInit_C=0x5B08
ADD_LINKER_FLAGS   += -Wl,--defsym=API_initPollingConfiguration_C=0x5B0C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_initRssiConfiguration_C=0x5B10
ADD_LINKER_FLAGS   += -Wl,--defsym=API_initFacLockedArea_C=0x5B14
ADD_LINKER_FLAGS   += -Wl,--defsym=API_clkSwitchFRC_C=0x5B18
ADD_LINKER_FLAGS   += -Wl,--defsym=API_initChannelSwitchForCurrentService_C=0x5B1C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_clkSwitchXTO_ASM=0x5B20
ADD_LINKER_FLAGS   += -Wl,--defsym=API_copyEepSvc_ASM=0x5B24
ADD_LINKER_FLAGS   += -Wl,--defsym=API_copyEepChannel_ASM=0x5B28
ADD_LINKER_FLAGS   += -Wl,--defsym=API_copySramSvc_ASM=0x5B2C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_copySramChannel_ASM=0x5B30
ADD_LINKER_FLAGS   += -Wl,--defsym=API_doIdScan_C=0x5B34
ADD_LINKER_FLAGS   += -Wl,--defsym=API_initIoConfig_C=0x5B38
ADD_LINKER_FLAGS   += -Wl,--defsym=API_defaultIoConfig_C=0x5B3C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemInit_C=0x5B40
ADD_LINKER_FLAGS   += -Wl,--defsym=API_doInitialization_C=0x5B44
ADD_LINKER_FLAGS   += -Wl,--defsym=API_checkWakeupSource_C=0x5B48
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemCalibAtStartup_C=0x5B4C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_startInitTxRxSSM_C=0x5B50
ADD_LINKER_FLAGS   += -Wl,--defsym=API_startShutDownSSM_C=0x5B54
ADD_LINKER_FLAGS   += -Wl,--defsym=API_ssmInterrupt_C=0x5B58
ADD_LINKER_FLAGS   += -Wl,--defsym=API_IDscanBufferFullInterrupt_C=0x5B5C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_resetSSMs_C=0x5B60
ADD_LINKER_FLAGS   += -Wl,--defsym=API_switchIdleXTO_ASM=0x5B64
ADD_LINKER_FLAGS   += -Wl,--defsym=API_setRxActive_ASM=0x5B68
ADD_LINKER_FLAGS   += -Wl,--defsym=API_clrRxActive_ASM=0x5B6C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_setSystemError_ASM=0x5B70
ADD_LINKER_FLAGS   += -Wl,--defsym=API_dataFifoOverUnderFlowHandler_ASM=0x5B74
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rssiPreambleFifoOverUnderFlowHandler_ASM=0x5B78
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pollStateInitCurrentPollingChannel_C=0x5B7C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pollStateInitSSM_C=0x5B80
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pollStateWait4SSMstateGetTelegram_C=0x5B84
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pollStateWait4ShutdownRdyTRX_C=0x5B88
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pollStateCheck4NextPollingChannel_C=0x5B8C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pollStateISR_ASM=0x5B90
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rxStateInitSSM_C=0x5B94
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rxStateStartSSM_C=0x5B98
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rxStateWait4SSMstateGetTelegram_C=0x5B9C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rxStateWait4SSMrdy_C=0x5BA0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_pureRxUp_C=0x5BA4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rssiStateInitSSM_C=0x5BA8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rssiStateWait4SSMrdy_C=0x5BAC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rssiStateStartSSM_C=0x5BB0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rxStateInitSubchanneling_C=0x5BB4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rxStateSubchanneling_Center_Freq_C=0x5BB8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rxStateSubchanneling_Lower_Freq_C=0x5BBC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rxStateSubchanneling_Upper_Freq_C=0x5BC0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_wakeCheckOkPathB_ASM=0x5BC4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_wakeCheckOkPathA_ASM=0x5BC8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_startOfTelegramPathB_ASM=0x5BCC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_startOfTelegramPathA_ASM=0x5BD0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_endOfTelegramPathB_ASM=0x5BD4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_endOfTelegramPathA_ASM=0x5BD8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_dataFifoFillLevelReached_ASM=0x5BDC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_rssiPreambleFifoFillLevelReached_ASM=0x5BE0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_txStateInitSSM_C=0x5BE4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_txStateStartSSM_C=0x5BE8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_txStateWait4SSMrdy_C=0x5BEC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_txTransparentStateWait4SSMrdy_C=0x5BF0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_txStateTransparentMode_C=0x5BF4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_txStateWait4FillLevel_C=0x5BF8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_txStateStartTxModulator_C=0x5BFC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_txStateStartWait4TransmissionComplete_C=0x5C00
ADD_LINKER_FLAGS   += -Wl,--defsym=API_openTimer3forTxing_C=0x5C04
ADD_LINKER_FLAGS   += -Wl,--defsym=API_sysTxingBufferedMode_C=0x5C08
ADD_LINKER_FLAGS   += -Wl,--defsym=API_sysTxingTransparentMode_C=0x5C0C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_TxModulatorTelegramFinish_ASM=0x5C10
ADD_LINKER_FLAGS   += -Wl,--defsym=API_check4extRequests_C=0x5C14
ADD_LINKER_FLAGS   += -Wl,--defsym=API_serviceInitSwitching_C=0x5C18
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemFlowCtrl_C=0x5C1C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_sysExeStateMachineFunc_C=0x5C20
ADD_LINKER_FLAGS   += -Wl,--defsym=API_setIdleMode_C=0x5C24
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemFlowStateWaitXtoReady_C=0x5C28
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemStartSSM_C=0x5C2C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemWait4SSMrdy_C=0x5C30
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemFlowStateShutdownTRX_C=0x5C34
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemFlowStateWait4ShutdownRdyTRX_C=0x5C38
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemFlowStateMachineEnd_C=0x5C3C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemErrorLoop_C=0x5C40
ADD_LINKER_FLAGS   += -Wl,--defsym=API_lowBatt_C=0x5C44
ADD_LINKER_FLAGS   += -Wl,--defsym=API_avccLow_C=0x5C48
ADD_LINKER_FLAGS   += -Wl,--defsym=API_avccReset_C=0x5C4C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_triggerSrcCalibration_C=0x5C50
ADD_LINKER_FLAGS   += -Wl,--defsym=API_triggerFrcCalibration_C=0x5C54
ADD_LINKER_FLAGS   += -Wl,--defsym=API_triggerSelfCheck_C=0x5C58
ADD_LINKER_FLAGS   += -Wl,--defsym=API_wait4avcc_C=0x5C5C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_systemModeSwitching_C=0x5C60
ADD_LINKER_FLAGS   += -Wl,--defsym=API_tuneCheckSwitching_C=0x5C64
ADD_LINKER_FLAGS   += -Wl,--defsym=API_miscTriggerSwitching_C=0x5C68
ADD_LINKER_FLAGS   += -Wl,--defsym=API_setEventPin_ASM=0x5C6C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer1Open_C=0x5C70
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer1Close_ASM=0x5C74
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer1ComIntHandler_ASM=0x5C78
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer1OvfIntHandler_ASM=0x5C7C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer2Open_C=0x5C80
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer2Close_ASM=0x5C84
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer2ComIntHandler_ASM=0x5C88
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer2OvfIntHandler_ASM=0x5C8C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer3Open_C=0x5C90
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer3Close_ASM=0x5C94
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer3ComIntHandler_ASM=0x5C98
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer3OvfIntHandler_ASM=0x5C9C
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer3CapIntHandler_ASM=0x5CA0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer4Open_C=0x5CA4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer4Close_ASM=0x5CA8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer4ComIntHandler_ASM=0x5CAC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer4OvfIntHandler_ASM=0x5CB0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer4CapIntHandler_ASM=0x5CB4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer5Open_C=0x5CB8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer5Close_ASM=0x5CBC
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer5ComIntHandler_ASM=0x5CC0
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer5OvfIntHandler_ASM=0x5CC4
ADD_LINKER_FLAGS   += -Wl,--defsym=API_stopSsmWatchdog_C=0x5CC8
ADD_LINKER_FLAGS   += -Wl,--defsym=API_timer1ResetRun_ASM=0x5CCC
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rfCalibration_C=0x3A6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_anttuneStateInitSSM_C=0x49E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_sysAntTuneSsmEnable_C=0x4A2
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_anttuneStateStartSSM_C=0x4B0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_anttuneStateWait4SSMrdy_C=0x4BC
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_anttuneStateSetCmdRdy_C=0x4DE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_vcocalStateInitSSM_C=0x4F0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_sysVcoCalSsmEnable_C=0x4F4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_vcocalStateStartSSM_C=0x502
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_vcocalStateWait4SSMrdy_C=0x50E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_vcocalStateSetCmdRdy_C=0x530
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_tempmeasStateInitSSM_C=0x54C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_sysTempMeasSsmEnable_C=0x550
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_startInitTempMeasSSM_C=0x564
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_configureTempMeasSSM_C=0x5EE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_tempmeasStateStartSSM_C=0x626
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_tempmeasStateWait4SSMrdy_C=0x632
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_tempmeasStateWait4Temperature_C=0x63A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_tempmeasStateSetCmdRdy_C=0x6CA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_checkModulationType4TX_ASM=0x6E6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_frcCalib_ASM=0x704
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_frcMeas_ASM=0x734
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_getT2T3_ASM=0x7C6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_srcCalib_ASM=0x7FA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_correctTimer1CompVal_ASM=0x808
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_shiftRightInt32_ASM=0x89A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_shiftRightInt16_ASM=0x8AA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_srcMeas_ASM=0x824
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_eepWRbyte_C=0x8B6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_eepWRblock_C=0x8D0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_eepRDblock_C=0x904
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_eepromSecureWrite_C=0x932
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_eepRDbyte_ASM=0x952
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_SpiOpen_C=0x960
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_spiClose_C=0x4F70
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initExtIf_C=0x9A6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_PatchSpiReady_ASM=0x9C0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pinChangeInterrupt0Handler_ASM=0x9C4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pinChangeInterrupt1Handler_ASM=0x9E6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_SpiClose_ASM=0xA08
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_spiSerialTransferCompleteHandler_ASM=0xAC4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_spiRxBufferHandler_ASM=0x11D2
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_spiTxBufferHandler_ASM=0x11F8
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_portBisr_ASM=0x121E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_portCisr_ASM=0x124C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pureRxModeCtrl_ASM=0x1274
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pureRxModeCtrl_v212_ASM=0x4FB6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_interrupt0Handler_ASM=0x12B4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_interrupt1Handler_ASM=0x12D6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_setClk_C=0x1382
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_wdtDisable_C=0x1390
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_wdtEnable_C=0x13AA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_SleepMode_C=0x13E0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_Sleep_C=0x141A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_currentServiceInit_C=0x1442
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initPollingConfiguration_C=0x150C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initRssiConfiguration_C=0x1528
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initFacLockedArea_C=0x153E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_clkSwitchFRC_C=0x154C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initChannelSwitchForCurrentService_C=0x1586
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_clkSwitchXTO_ASM=0x15EE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_mulU8U8_ASM=0x160E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_mulS8U8_ASM=0x161E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_mpy16u_ASM=0x162E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_mpy16u=0x163C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_mpy16s_ASM=0x165E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_mpy16s=0x166C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_waitNus_ASM=0x168E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_mulU8UbyCor_ASM=0x1698
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_divU16U8_ASM=0x16BE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_copyEepSvc_ASM=0x16F8
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_copyEepChannel_ASM=0x1910
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_copySramSvc_ASM=0x1944
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_copySramChannel_ASM=0x1B4A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_doIdScan_C=0x1B6C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_doIdSubScan_C=0x1C66
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initIoConfig_C=0x1D12
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_defaultIoConfig_C=0x1D58
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemInit_C=0x1D6A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_doInitialization_C=0x1E7E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_checkWakeupSource_C=0x209E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initStateMachines_C=0x20E2
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemCalibAtStartup_C=0x2178
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_resetSSMs_C=0x2216
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_startInitTxRxSSM_C=0x2272
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_startShutDownSSM_C=0x2314
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_doFeInit4TxRxSSM_C=0x235A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_doFevcoRegisterCalculation_C=0x2416
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_shutDownRf_C=0x245A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_shutDownFe_C=0x2480
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pwrDwnDsp_C=0x24D4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_ssmInterrupt_C=0x250C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_IDscanBufferFullInterrupt_C=0x2520
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_switchIdleXTO_ASM=0x2542
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_setRxActive_ASM=0x25AA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_clrRxActive_ASM=0x25C2
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_setSystemError_ASM=0x25DA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_dataFifoOverUnderFlowHandler_ASM=0x25EA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rssiPreambleFifoOverUnderFlowHandler_ASM=0x261C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pollStateInitCurrentPollingChannel_C=0x264E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pollStateInitSSM_C=0x26A6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pollStateWait4SSMstateGetTelegram_C=0x2718
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pollStateWait4ShutdownRdyTRX_C=0x27B4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pollStateCheck4NextPollingChannel_C=0x282E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pollStateISR_ASM=0x29CC
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_doFrequencySettingsRx_C=0x2A12
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_startInitRxSSM_C=0x2A4C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_configureRxSSM_C=0x2B4E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initCorrelator_C=0x2CA8
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initRxBuffer_C=0x2D6A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_initRssiBuffer_C=0x2DE4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxStateInitSSM_C=0x2E26
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxStateStartSSM_C=0x2E76
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxStateWait4SSMstateGetTelegram_C=0x2F54
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxStateWait4SSMrdy_C=0x2FE6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_pureRxUp_C=0x3114
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rssiStateInitSSM_C=0x3118
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rssiStateWait4SSMrdy_C=0x315C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rssiStateStartSSM_C=0x316E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxStateInitSubchanneling_C=0x31A4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxStateSubchanneling_Center_Freq_C=0x320E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxStateSubchanneling_Lower_Freq_C=0x32EA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxStateSubchanneling_Upper_Freq_C=0x33AE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxIntConfPathA_C=0x34F0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rxIntConfPathB_C=0x3510
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_signalEotAtSsmRdy_C=0x3530
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_wakeCheckOkPathB_ASM=0x358E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_wakeCheckOkPathA_ASM=0x361C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_startOfTelegramPathB_ASM=0x36A6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_startOfTelegramPathA_ASM=0x3712
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_endOfTelegramPathB_ASM=0x377A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_endOfTelegramPathA_ASM=0x37DE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_dataFifoFillLevelReached_ASM=0x3842
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_rssiPreambleFifoFillLevelReached_ASM=0x38A4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_startInitTxSSM_C=0x3902
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_configureTxSSM_C=0x3964
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_doFrequencySettingsTx_C=0x3A52
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_openTimer3forTxing_C=0x3B00
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_sysTxingBufferedMode_C=0x3B4A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_sysTxingTransparentMode_C=0x3B6A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_setupTxModulator_C=0x3B8E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_txStateInitSSM_C=0x3C3E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_txStateStartSSM_C=0x3C6A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_txStateWait4SSMrdy_C=0x3C76
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_txTransparentStateWait4SSMrdy_C=0x3CAC
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_txStateTransparentMode_C=0x3CE2
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_txStateWait4FillLevel_C=0x3CE6
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_txStateStartTxModulator_C=0x3D28
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_txStateStartWait4TransmissionComplete_C=0x3D98
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_TxModulatorTelegramFinish_ASM=0x3DDE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_SignatureTestAsm=0x5010
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_check4extRequests_C=0x3E20
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemModeSwitching_C=0x3E50
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_tuneCheckSwitching_C=0x4038
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_serviceInitSwitching_C=0x410E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_miscTriggerSwitching_C=0x419A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemFlowCtrl_C=0x41E0
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_sysExeStateMachineFunc_C=0x41E2
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_sysIdleMode_C=0x420C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_setIdleMode_C=0x421C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemFlowStateWaitXtoReady_C=0x426C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemStartSSM_C=0x4296
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemWait4SSMrdy_C=0x42D8
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemFlowStateShutdownTRX_C=0x432E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemFlowStateWait4ShutdownRdyTRX_C=0x4354
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemFlowStateMachineEnd_C=0x43C4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_systemErrorLoop_C=0x43E2
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_startSsmWatchdog_C=0x43FA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_stopSsmWatchdog_C=0x442E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_lowBatt_C=0x4432
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_avccLow_C=0x448A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_avccReset_C=0x44E2
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_checkAndSwitchIdleXTO_C=0x44FA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_triggerSrcCalibration_C=0x450A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_triggerFrcCalibration_C=0x453A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_triggerSelfCheck_C=0x456A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_wait4avcc_C=0x45DA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_blockingShutDownSSM_C=0x4642
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_setEventPin_ASM=0x4696
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer1Open_C=0x46AC
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer1Close_ASM=0x46DE
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer1ComIntHandler_ASM=0x46F4
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer1OvfIntHandler_ASM=0x4716
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer1ResetRun_ASM=0x4738
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer2Open_C=0x4744
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer2Close_ASM=0x4776
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer2ComIntHandler_ASM=0x4788
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer2OvfIntHandler_ASM=0x47AA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer2ResetRun_ASM=0x47CC
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer3Open_C=0x47D8
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer3Close_ASM=0x4818
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer3ComIntHandler_ASM=0x482A
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer3OvfIntHandler_ASM=0x4854
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer3CapIntHandler_ASM=0x4876
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer4Open_C=0x4898
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer4Close_ASM=0x48D8
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer4ComIntHandler_ASM=0x48EA
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer4OvfIntHandler_ASM=0x490C
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer4CapIntHandler_ASM=0x492E
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer5Open_C=0x4950
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer5Close_ASM=0x4980
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer5ComIntHandler_ASM=0x4992
ADD_LINKER_FLAGS   += -Wl,--defsym=ATA_timer5OvfIntHandler_ASM=0x49B4
ADD_LINKER_FLAGS   += -Wl,--defsym=romVersion=0x04FFF

ADD_LINKER_FLAGS   += -Wl,--defsym=sysStatus=0x3B
ADD_LINKER_FLAGS   += -Wl,--defsym=events_system=0x0F
ADD_LINKER_FLAGS   += -Wl,--defsym=events_events=0x0E
ADD_LINKER_FLAGS   += -Wl,--defsym=events_power=0x0D
ADD_LINKER_FLAGS   += -Wl,--defsym=events_config=0x0C
ADD_LINKER_FLAGS   += -Wl,--defsym=trxStatus=0x3C
ADD_LINKER_FLAGS   += -Wl,--defsym=calib=0x2D8
ADD_LINKER_FLAGS   += -Wl,--defsym=frcResults=0x2F5
ADD_LINKER_FLAGS   += -Wl,--defsym=eepDebug=0x262
ADD_LINKER_FLAGS   += -Wl,--defsym=eepDebounce=0x263
ADD_LINKER_FLAGS   += -Wl,--defsym=eepServices=0xBB
ADD_LINKER_FLAGS   += -Wl,--defsym=eepPollLoopConf=0x99
ADD_LINKER_FLAGS   += -Wl,--defsym=eepFacLock=0x400
ADD_LINKER_FLAGS   += -Wl,--defsym=eepConfValid=0x08
ADD_LINKER_FLAGS   += -Wl,--defsym=eepIO=0x0D
ADD_LINKER_FLAGS   += -Wl,--defsym=eepTrxConf=0x15
ADD_LINKER_FLAGS   += -Wl,--defsym=eepTrxCal=0x1C
ADD_LINKER_FLAGS   += -Wl,--defsym=eepID=0x36
ADD_LINKER_FLAGS   += -Wl,--defsym=eepWdtConf=0x91
ADD_LINKER_FLAGS   += -Wl,--defsym=eepEventConf=0x94
ADD_LINKER_FLAGS   += -Wl,--defsym=eepSleepMode=0x97
ADD_LINKER_FLAGS   += -Wl,--defsym=eepFRCcalib=0x98
ADD_LINKER_FLAGS   += -Wl,--defsym=eepRssi=0x40A
ADD_LINKER_FLAGS   += -Wl,--defsym=eepVsPa=0x40D
ADD_LINKER_FLAGS   += -Wl,--defsym=eepServiceChannelSwitchConfig=0x267
ADD_LINKER_FLAGS   += -Wl,--defsym=eepVersion=0x00
ADD_LINKER_FLAGS   += -Wl,--defsym=extIf=0x200
ADD_LINKER_FLAGS   += -Wl,--defsym=customCmd=0x2FD
ADD_LINKER_FLAGS   += -Wl,--defsym=trxConf=0x2DF
ADD_LINKER_FLAGS   += -Wl,--defsym=events=0x20F
ADD_LINKER_FLAGS   += -Wl,--defsym=tmpAryApp=0x2E9
ADD_LINKER_FLAGS   += -Wl,--defsym=extReq=0x2F8
ADD_LINKER_FLAGS   += -Wl,--defsym=triggerEEPwr=0x2FF
ADD_LINKER_FLAGS   += -Wl,--defsym=sleepModeConfig=0x2F3
ADD_LINKER_FLAGS   += -Wl,--defsym=currentService=0x217
ADD_LINKER_FLAGS   += -Wl,--defsym=sramServices=0x328
ADD_LINKER_FLAGS   += -Wl,--defsym=facLock=0x2B5
ADD_LINKER_FLAGS   += -Wl,--defsym=debug=0x300
ADD_LINKER_FLAGS   += -Wl,--defsym=rssiThresholds=0x442
ADD_LINKER_FLAGS   += -Wl,--defsym=rssiAtWcok=0x460
ADD_LINKER_FLAGS   += -Wl,--defsym=frequencyOffsetAtWcok=0x46F
ADD_LINKER_FLAGS   += -Wl,--defsym=subChan=0x470
ADD_LINKER_FLAGS   += -Wl,--defsym=rxIrqEvents=0x474
ADD_LINKER_FLAGS   += -Wl,--defsym=sramServiceChannelSwitchConfig=0x477
ADD_LINKER_FLAGS   += -Wl,--defsym=sramPollingChannelStatistics=0x47B
ADD_LINKER_FLAGS   += -Wl,--defsym=lowestRssiOfCurPolCycle=0x47D
ADD_LINKER_FLAGS   += -Wl,--defsym=tempBestChannelPollingIndex=0x47E
ADD_LINKER_FLAGS   += -Wl,--defsym=tempBestChannelServiceChannelConfig=0x47F
ADD_LINKER_FLAGS   += -Wl,--defsym=rfPaCtrl=0x2F4
ADD_LINKER_FLAGS   += -Wl,--defsym=pollConfig=0x302
ADD_LINKER_FLAGS   += -Wl,--defsym=pollStatus=0x324
ADD_LINKER_FLAGS   += -Wl,--defsym=flowCtrl=0x29A
ADD_LINKER_FLAGS   += -Wl,--defsym=pAntTuneSysFlowStateMachine=0x2A7
ADD_LINKER_FLAGS   += -Wl,--defsym=pPollSysFlowStateMachine=0x2A5
ADD_LINKER_FLAGS   += -Wl,--defsym=pPureRxSysFlowStateMachine=0x2AB
ADD_LINKER_FLAGS   += -Wl,--defsym=pRssiSysFlowStateMachine=0x2AD
ADD_LINKER_FLAGS   += -Wl,--defsym=pRxSysFlowStateMachine=0x29F
ADD_LINKER_FLAGS   += -Wl,--defsym=pSelfCheckSysFlowStateMachine=0x2B1
ADD_LINKER_FLAGS   += -Wl,--defsym=pTempMeasSysFlowStateMachine=0x2AF
ADD_LINKER_FLAGS   += -Wl,--defsym=pTxBufSysFlowStateMachine=0x2A1
ADD_LINKER_FLAGS   += -Wl,--defsym=pTxTransSysFlowStateMachine=0x2A3
ADD_LINKER_FLAGS   += -Wl,--defsym=pVcoCalSysFlowStateMachine=0x2A9
ADD_LINKER_FLAGS   += -Wl,--defsym=pSubChannelingSysFlowStateMachine=0x2B3
ADD_LINKER_FLAGS   += -Wl,--defsym=timer1=0x2BB
ADD_LINKER_FLAGS   += -Wl,--defsym=timer2=0x2C0
ADD_LINKER_FLAGS   += -Wl,--defsym=timer3=0x2C5
ADD_LINKER_FLAGS   += -Wl,--defsym=timer4=0x2CC
ADD_LINKER_FLAGS   += -Wl,--defsym=timer5=0x2D3

