###############################################################################
#   $URL: http://svnservulm.corp.atmel.com/svn/CDB/Apps/Apps_SW/Trunk/SW_Projects/XC8/ATA8510_FLASH_XC8/ATA8510_FLASH.X/wrap_defines.mk $
#   $LastChangedRevision: 660705 $
#   $LastChangedDate: 2022-04-26 08:54:34 +0200 (Di, 26 Apr 2022) $
#   $LastChangedBy: gwillbol $
###############################################################################

# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ReadFillLevelRxBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ReadFillLevelTxBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ReadFillLevelRssiBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_GetEventBytes_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ReadRssiBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ReadRxBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_WriteSramRegisters_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ReadSramRegisters_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_WriteEeprom_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ReadEeprom_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_WriteTxBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_WriteTxPreambleBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_SetSystemMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_CalibrateAndCheck_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_GetRomVersion_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_GetFlashVersion_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_CustomerConfigurableCommand_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_SystemReset_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_TriggerEepromSecureWrite_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_SetVoltageMonitor_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_OffCommand_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ReadTemperature_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_InitSramService_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_StartRssiMeasurement_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_GetRssiAverageValue_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_GetRssiPeakValue_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_ReadFillLevelRxBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_ReadFillLevelTxBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_ReadFillLevelRssiBuffer_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_GetEventBytes_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_ReadRssiBuffer_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_ReadRxBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_WriteSramRegisters_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_ReadSramRegisters_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_WriteEeprom_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_ReadEeprom_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_WriteTxBuffer_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_WriteTxPreambleBuffer_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_SetSystemMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_CalibrateAndCheck_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_GetRomVersion_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_GetFlashVersion_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_CustomerConfigurableCommand_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_SystemReset_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_TriggerEepromSecureWrite_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_SetVoltageMonitor_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_OffCommand_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_ReadTemperature_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_InitSramService_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_StartRssiMeasurement_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_GetRssiAverageValue_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_GetRssiPeakValue_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rfCalibration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_anttuneStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_sysAntTuneSsmEnable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_anttuneStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_anttuneStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_anttuneStateSetCmdRdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_vcocalStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_sysVcoCalSsmEnable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_vcocalStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_vcocalStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_vcocalStateSetCmdRdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_tempmeasStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_sysTempMeasSsmEnable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_tempmeasStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_tempmeasStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_tempmeasStateWait4Temperature_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_tempmeasStateSetCmdRdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_eepWRbyte_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_eepWRblock_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_eepRDblock_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_eepromSecureWrite_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_eepRDbyte_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_SpiOpen_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_initExtIf_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_PatchSpiReady_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_SpiClose_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_portBisr_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_portCisr_ASM
ADD_LINKER_FLAGS   += -Wl,--wrap=API_setClk_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_wdtDisable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_wdtEnable_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_SleepMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_Sleep_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_currentServiceInit_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_initPollingConfiguration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_initRssiConfiguration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_initFacLockedArea_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_clkSwitchFRC_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_initChannelSwitchForCurrentService_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_clkSwitchXTO_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_copyEepSvc_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_copyEepChannel_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_copySramSvc_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_copySramChannel_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_doIdScan_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_initIoConfig_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_defaultIoConfig_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemInit_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_doInitialization_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_checkWakeupSource_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemCalibAtStartup_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_startInitTxRxSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_startShutDownSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_ssmInterrupt_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_resetSSMs_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_switchIdleXTO_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_setRxActive_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_clrRxActive_ASM
ADD_LINKER_FLAGS   += -Wl,--wrap=API_setSystemError_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_pollStateInitCurrentPollingChannel_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_pollStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_pollStateWait4SSMstateGetTelegram_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_pollStateWait4ShutdownRdyTRX_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_pollStateCheck4NextPollingChannel_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_pollStateISR_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rxStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rxStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rxStateWait4SSMstateGetTelegram_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rxStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_pureRxUp_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rssiStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rssiStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rssiStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rxStateInitSubchanneling_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rxStateSubchanneling_Center_Freq_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rxStateSubchanneling_Lower_Freq_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_rxStateSubchanneling_Upper_Freq_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txTransparentStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txStateTransparentMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txStateTransparentMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txStateWait4FillLevel_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txStateStartTxModulator_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_txStateStartWait4TransmissionComplete_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_openTimer3forTxing_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_sysTxingBufferedMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_sysTxingTransparentMode_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_check4extRequests_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_serviceInitSwitching_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemFlowCtrl_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_sysExeStateMachineFunc_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_setIdleMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemFlowStateWaitXtoReady_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemFlowStateShutdownTRX_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemFlowStateWait4ShutdownRdyTRX_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemFlowStateMachineEnd_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemErrorLoop_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_triggerSrcCalibration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_triggerFrcCalibration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_triggerSelfCheck_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_wait4avcc_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_systemModeSwitching_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_tuneCheckSwitching_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_miscTriggerSwitching_C
ADD_LINKER_FLAGS   += -Wl,--wrap=API_setEventPin_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_timer1Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_timer2Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_timer3Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_timer4Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_timer5Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_stopSsmWatchdog_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=API_timer1ResetRun_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rfCalibration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_anttuneStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_sysAntTuneSsmEnable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_anttuneStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_anttuneStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_anttuneStateSetCmdRdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_vcocalStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_sysVcoCalSsmEnable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_vcocalStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_vcocalStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_vcocalStateSetCmdRdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_tempmeasStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_sysTempMeasSsmEnable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_startInitTempMeasSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_configureTempMeasSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_tempmeasStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_tempmeasStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_tempmeasStateWait4Temperature_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_tempmeasStateSetCmdRdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_checkModulationType4TX_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_frcCalib_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_frcMeas_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_getT2T3_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_srcCalib_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_correctTimer1CompVal_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_shiftRightInt32_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_shiftRightInt16_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_srcMeas_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_eepWRbyte_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_eepWRblock_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_eepRDblock_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_eepromSecureWrite_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_eepRDbyte_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_SpiOpen_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_spiClose_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initExtIf_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_PatchSpiReady_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_SpiClose_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_portBisr_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_portCisr_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pureRxModeCtrl_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pureRxModeCtrl_v212_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_setClk_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_wdtDisable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_wdtEnable_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_SleepMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_Sleep_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_currentServiceInit_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initPollingConfiguration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initRssiConfiguration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initFacLockedArea_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_clkSwitchFRC_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initChannelSwitchForCurrentService_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_clkSwitchXTO_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_mulU8U8_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_mulS8U8_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_mpy16u_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_mpy16s_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_waitNus_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_mulU8UbyCor_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_divU16U8_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_copyEepSvc_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_copyEepChannel_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_copySramSvc_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_copySramChannel_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_doIdScan_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_doIdSubScan_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initIoConfig_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_defaultIoConfig_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemInit_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_doInitialization_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_checkWakeupSource_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initStateMachines_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemCalibAtStartup_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_resetSSMs_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_startInitTxRxSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_startShutDownSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_doFeInit4TxRxSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_doFevcoRegisterCalculation_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_shutDownRf_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_shutDownFe_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pwrDwnDsp_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_ssmInterrupt_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_switchIdleXTO_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_setRxActive_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_clrRxActive_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_setSystemError_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pollStateInitCurrentPollingChannel_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pollStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pollStateWait4SSMstateGetTelegram_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pollStateWait4ShutdownRdyTRX_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pollStateCheck4NextPollingChannel_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pollStateISR_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_doFrequencySettingsRx_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_startInitRxSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_configureRxSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initCorrelator_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initRxBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_initRssiBuffer_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxStateWait4SSMstateGetTelegram_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_pureRxUp_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rssiStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rssiStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rssiStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxStateInitSubchanneling_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxStateSubchanneling_Center_Freq_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxStateSubchanneling_Lower_Freq_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxStateSubchanneling_Upper_Freq_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxIntConfPathA_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_rxIntConfPathB_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_signalEotAtSsmRdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_startInitTxSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_configureTxSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_doFrequencySettingsTx_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_openTimer3forTxing_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_sysTxingBufferedMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_sysTxingTransparentMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_setupTxModulator_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_txStateInitSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_txStateStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_txStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_txTransparentStateWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_txStateTransparentMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_txStateWait4FillLevel_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_txStateStartTxModulator_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_txStateStartWait4TransmissionComplete_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_check4extRequests_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemModeSwitching_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_tuneCheckSwitching_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_serviceInitSwitching_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_miscTriggerSwitching_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemFlowCtrl_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_sysExeStateMachineFunc_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_sysIdleMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_setIdleMode_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemFlowStateWaitXtoReady_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemStartSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemWait4SSMrdy_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemFlowStateShutdownTRX_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemFlowStateWait4ShutdownRdyTRX_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemFlowStateMachineEnd_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_systemErrorLoop_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_startSsmWatchdog_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_stopSsmWatchdog_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_checkAndSwitchIdleXTO_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_triggerSrcCalibration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_triggerFrcCalibration_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_triggerSelfCheck_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_wait4avcc_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_blockingShutDownSSM_C
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_setEventPin_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_timer1Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_timer1ResetRun_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_timer2Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_timer2ResetRun_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_timer3Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_timer4Close_ASM
# ADD_LINKER_FLAGS   += -Wl,--wrap=ATA_timer5Close_ASM
